### PR TITLE
Add docker 'volumes-from' option support

### PR DESCRIPTION
**Pull request by waynz0r**

### CODE REVIEW

**Comment by alde** [comment]
Hi

Thanks for the PR

Could you give some information about what this is for, and also update the README?

**Comment by waynz0r** [comment]
Hi,

it adds support for the 'volumes-from' option of docker. See https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container-volumes-from

We are using Mesos to run thousands of small computations on our cluster in parallel, each running in a docker container and we use this option to keep the calculation images as small in size as possible.

**Comment by keis** [comment]
LGTM, but as @alde said needs readme and also swagger updated.

**Comment by waynz0r** [comment]
I changed the variable naming, feels better this way. Also updated the README and the Swagger definitions.

**Comment by alde** [comment]
I also much prefer this new name.

LGTM. Thanks for the PR!

**Pull request merged**
