### PR TITLE
Add a 'privileged' flag to allow running privileged containers in eremetic.

### PR DESCRIPTION
**Pull request by barryw**
Updated formatting.

### CODE REVIEW

**Comment by keis** [comment]
Thanks for the PR

Could you make sure to update the example in the readme and the swagger with the new parameter?

**Comment by barryw** [comment]
Will do.

**Comment by keis** [comment]
ty, but looks like you accidentally merged something into the branch

**Comment by amanelis** [comment]
@keis my bad looks like had a little git hiccup, fixed. Not sure about the coveralls failing. what ya think?

**Comment by alde** [comment]
Well, the coverage went down with .009%, so I don't think it matters.
The viewing/launching a task through the GUI won't include the privileged flag, but I'm slowly working on a new and more easily-worked GUI, so I don't think that's strictly necessary.

Also not sure it was necessary to add to the deprecated V0 api, but now that you already have I won't argue against it.

All in all, looks good to me

**Comment by keis** [comment]
LGTM

**Pull request merged**
