### PR TITLE
Random stuck

### LINKED ISSUE #187: Tasks randomly get stuck in TASK_QUEUED state
Hey guys,

just ran into an interesting issue with eremetic `v0.28.0`. 
Tasks run normally in our environment (Mesos `v.1.3.1`), so this is not related to a wrong setup of Eremetic.
Sometimes a task doesn't get beyond `TASK_QUEUED` state.

This is how it looks in eremetic logs:
```
time="2017-10-16T17:52:37Z" level=debug msg="Adding task to queue" agent_constraints=[] command="<redacted>" docker_image="<redacted>" ports=[] 
time="2017-10-16T17:52:37Z" level=debug msg="Received offers" offers=10 
time="2017-10-16T17:52:37Z" level=debug msg="Trying to find offer to launch task with" task_id=eremetic-task.0a7f3bbc-4548-41ee-90ac-12c11dd3fc36 
time="2017-10-16T17:52:37Z" level=debug msg="Preparing to launch task" offer_id=8acb9e52-ac67-43ff-8e28-614c5f6bbde6-O12193954 task_id=eremetic-task.0a7f3bbc-4548-41ee-90ac-12c11dd3fc36 
time="2017-10-16T17:52:37Z" level=debug msg="No tasks to launch. Declining offers." 
time="2017-10-16T17:52:37Z" level=debug msg="Received task status update" status="TASK_ERROR" task_id= 
time="2017-10-16T17:52:37Z" level=debug msg="No Data in task status." 
```

This is how it looks in mesos-master logs:
```
I1016 17:52:37.645774 41484 master.cpp:6532] Sending status update TASK_ERROR for task  of framework Eremetic 'ID must not be empty'
```

After re-submitting the very same task to eremetic, it worked just fine. Similar tasks (up to a parameter) has succeeded before in the same instance of eremetic 16 times, with 119 other tasks ran successfully as well.

Would be nice to safeguard somehow for tasks not being launched, otherwise the task execution can at random become unreliable. E.g. timeout when expecting a message about the task launch from Mesos or smth.

### PR DESCRIPTION
**Pull request by ja8zyjits**
fixes #187 

I just saw the flow of logs, and thought of doing this workaround, will this fix?

The chief issue is the inability to reproduce the issue.

### CODE REVIEW

**Comment by keis** [comment]
Hey, just had a look (Sorry for the months long delay) and it looks like the asset build tool we are using started producing a broken generated file.

Sadly that project seems a bit abandoned too https://github.com/elazarl/go-bindata-assetfs/issues https://twitter.com/francesc/status/961249107020001280

**Comment by ja8zyjits** [comment]
@keis Thanks for the response.
I have my local copy of `go.mod` updated, but didn't push it. I thought it wont be wise to add other dependencies.
this is how my local copy differs
```bash
diff --git a/go.mod b/go.mod
index ffb8cd2..e09f608 100644
--- a/go.mod
+++ b/go.mod
@@ -8,6 +8,7 @@ require (
        github.com/braintree/manners v0.0.0-20150503212558-0b5e6b2c2843
        github.com/davecgh/go-spew v1.1.1
        github.com/elazarl/go-bindata-assetfs v1.0.0
+       github.com/go-bindata/go-bindata v3.1.2+incompatible // indirect
        github.com/gogo/protobuf v0.0.0-20170307180453-100ba4e88506
        github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
        github.com/golang/protobuf v0.0.0-20171021043952-1643683e1b54
@@ -15,11 +16,15 @@ require (
        github.com/gorilla/mux v1.4.0
        github.com/gorilla/schema v0.0.0-20171101174852-e6c82218a8b3
        github.com/jacobsa/oglematchers v0.0.0-20150720000706-141901ea67cd
+       github.com/jacobsa/oglemock v0.0.0-20150831005832-e94d794d06ff // indirect
+       github.com/jacobsa/ogletest v0.0.0-20170503003838-80d50a735a11 // indirect
+       github.com/jacobsa/reqtrace v0.0.0-20150505043853-245c9e0234cb // indirect
        github.com/kardianos/osext v0.0.0-20170510131534-ae77be60afb1
        github.com/kelseyhightower/envconfig v1.3.0
        github.com/kevinburke/go-bindata v3.13.0+incompatible // indirect
        github.com/matttproud/golang_protobuf_extensions v1.0.1
        github.com/mesos/mesos-go v0.0.0-20170604182343-f2cd423e881b
+       github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
        github.com/pborman/uuid v0.0.0-20160209185913-a97ce2ca70fa
        github.com/pmezard/go-difflib v1.0.0
        github.com/prometheus/client_golang v0.8.0
@@ -28,11 +33,13 @@ require (
        github.com/prometheus/procfs v0.0.0-20171017214025-a6e9df898b13
        github.com/samuel/go-zookeeper v0.0.0-20171027001500-9a96098268ef
        github.com/sirupsen/logrus v1.4.2
-       github.com/smartystreets/goconvey v0.0.0-20190330032615-68dc04aab96a
+       github.com/smartystreets/goconvey v1.6.4
        github.com/stretchr/objx v0.1.1
        github.com/stretchr/testify v1.2.2
        golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
        golang.org/x/net v0.0.0-20190311183353-d8887717615a
+       golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208 // indirect
        golang.org/x/sys v0.0.0-20190422165155-953cdadca894
+       gopkg.in/check.v1 v1.0.0-20200902074654-038fdea0a05b // indirect
        gopkg.in/yaml.v2 v2.0.0-20170812160011-eb3733d160e7
 )
```
Is it ok to add these changes?

**Comment by ja8zyjits** [comment]
@keis I have updated the tests and fixed the ci.
Please let me know if there is anything more you would like me to do.

**Comment by ja8zyjits** [comment]
> Hey, just had a look (Sorry for the months long delay) and it looks like the asset build tool we are using started producing a broken generated file.
> 
> Sadly that project seems a bit abandoned too https://github.com/elazarl/go-bindata-assetfs/issues https://twitter.com/francesc/status/961249107020001280

That security issue seems to be fixed with new repo `https://github.com/go-bindata/go-bindata` replacing the old one.

**Comment by keis** [comment]
@ja8zyjits Ok that's great! I'll go ahead and merge this then :)

**Comment by ja8zyjits** [comment]
@keis , thanks for the prompt response.
We have 3 master commits yet to released, i.e April, May and December Commits.
It would be great if you release it. I shall update in the mesophere universe repo.

**Comment by keis** [comment]
Sure thing, I tagged a release but still need to wait for a travis run to get a the new docker image

**Comment by ja8zyjits** [comment]
https://github.com/mesosphere/universe/pull/2618
added pull request.

**Pull request merged**
